---

# *** Ensure dirs.

- name: Ensure the working directory exists
  file: path={{ zoidy_matecocido_working_dir }} state=directory

# *** Record start states.

- name: Record stock gsettings
  ansible.builtin.shell: "dbus-launch gsettings list-recursively | sort > {{ zoidy_matecocido_gsettings_begin }}"
  args:
    # Skip this task once the dump file exists.
    creates: "{{ zoidy_matecocido_gsettings_begin }}"

# FIXME/2018-12-15: Also dump gconftool-2 settings? Not that we change them.
#    gconftool-2 --dump / > cmd-gconftool-2.txt

- name: Record stock dconf
  ansible.builtin.shell: "dbus-launch dconf dump / > {{ zoidy_matecocido_dconf_begin }}"
  args:
    # Skip this task once the dump file exists.
    creates: "{{ zoidy_matecocido_dconf_begin }}"

# ======================================================================= #

# *** Make changes.

- name: Load role to Hide Desktop icons
  include_role:
    name: zoidy_matecocido
    tasks_from: background-hide_icons-go_black
    apply:
      tags:
        - background-hide_icons-go_black
  tags: background-hide_icons-go_black

- name: Add Alt-q Alt-tab binding
  include_role:
    name: zoidy_matecocido
    tasks_from: alt-tab-alt-q-to-go-backward
    apply:
      tags:
        - alt-tab-alt-q-to-go-backward
  tags: alt-tab-alt-q-to-go-backward

- name: Load role to eliminate MATE Alt-Tab slugishness
  include_role:
    name: zoidy_matecocido
    tasks_from: alt-tab-eliminate-delay
    apply:
      tags:
        - alt-tab-eliminate-delay
  tags: alt-tab-eliminate-delay

# The Hack font is used by: meld-configure, and terminal-configure.
# (And preffered by Dubs Vim <https://github.com/landonb/dubs-vim>.)
- name: Load role to Install Font “Hack”
  include_role:
    name: zoidy_matecocido
    tasks_from: font-hack
    apply:
      tags:
        - font-hack
        - meld-configure
        # 2020-02-07: Disabling for now, b/c make terminal-configure require -K.
        # - terminal-configure
  tags: font-hack, meld-configure, terminal-configure

- name: Load role to Customize MATE Key Bindings
  include_role:
    name: zoidy_matecocido
    tasks_from: keybinding-circus
    apply:
      tags:
        - keybinding-circus
        - reset-keybindings
  tags: keybinding-circus, reset-keybindings

- name: Load role to Customize MATE Appearance
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-appearance-configure
    apply:
      tags:
        - mate-appearance-configure
  tags: mate-appearance-configure

- name: Load role to Customize MATE Menu
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-main-menu-customize
    apply:
      tags:
        - mate-main-menu-customize
  tags: mate-main-menu-customize

- name: Load role to Customize MATE Marco Window-Keybindings
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-marco-window-keybindings
    apply:
      tags:
        - mate-marco-window-keybindings
  tags: mate-marco-window-keybindings

- name: Load role to Configure caja File Browser
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-caja-preferences
    apply:
      tags:
        - mate-caja-preferences
  tags: mate-caja-preferences

- name: Load role to Configure caja Media Handling
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-media-handling
    apply:
      tags:
        - mate-media-handling
  tags: mate-media-handling

- name: Load role to Configure Meld Preferences
  include_role:
    name: zoidy_matecocido
    tasks_from: meld-configure
    apply:
      tags:
        - meld-configure
  tags: meld-configure

# ***

- name: Determine if host is “Desktop” or “Laptop”
  # (lb): Response should be either "Desktop" or "Notebook", at least what I've seen.
  ansible.builtin.shell: dmidecode --string chassis-type
  become: yes
  register: chassis_type
  tags: power-management-prefs-laptop

# (lb): It does not hurt to configure these setting on a Desktop,
# but for completeness, we'll restrict this task to Laptop hosts.
- name: Load role to Fiddle About Laptop Power Settings
  include_role:
    name: zoidy_matecocido
    tasks_from: power-management-prefs-laptop
    apply:
      tags:
        - power-management-prefs-laptop
  tags: power-management-prefs-laptop
  when: chassis_type.stdout == 'Notebook'

# ***

- name: Load role to Configure MATE Take Screenshot
  include_role:
    name: zoidy_matecocido
    tasks_from: screenshot-configure
    apply:
      tags:
        - screenshot-configure
  tags: screenshot-configure

- name: Load role to Disable screensaver, and its lock
  include_role:
    name: zoidy_matecocido
    tasks_from: screensaver-tweak
    apply:
      tags:
        - screensaver-tweak
  tags: screensaver-tweak

# ***

- name: Load role to ensure Ansible dconf module available
  include_role:
    name: zoidy_matecocido
    tasks_from: ansible-ensure-dconf
    apply:
      tags:
        - ansible-ensure-dconf
        # 2020-02-07: The terminal-configure task uses dconf module,
        #             but doesn't require sudo/-K, unless we want to
        #             call ansible-ensure-dconf...
        # - terminal-configure
  tags: ansible-ensure-dconf, terminal-configure

- name: Load role to Configure mate-terminal
  include_role:
    name: zoidy_matecocido
    tasks_from: terminal-configure
    apply:
      tags:
        - terminal-configure
  tags: terminal-configure

# ======================================================================= #

# *** Record final states.

- name: Record final gsettings
  ansible.builtin.shell: "dbus-launch gsettings list-recursively | sort > {{ zoidy_matecocido_gesttings_dated }}"

- name: Record final dconf
  ansible.builtin.shell: "dbus-launch dconf dump / > {{ zoidy_matecocido_dconf_dated }}"

