---

# *** Ensure dirs.

- name: Ensure the working directory exists
  file: path={{ zoidy_matecocido_working_dir }} state=directory

# *** Record start states.

- name: Record stock gsettings
  shell: "dbus-launch gsettings list-recursively | sort > {{ zoidy_matecocido_gsettings_begin }}"
  args:
    # Skip this task once the dump file exists.
    creates: "{{ zoidy_matecocido_gsettings_begin }}"

# FIXME/2018-12-15: Also dump gconftool-2 settings? Not that we change them.
#    gconftool-2 --dump / > cmd-gconftool-2.txt

- name: Record stock dconf
  shell: "dbus-launch dconf dump / > {{ zoidy_matecocido_dconf_begin }}"
  args:
    # Skip this task once the dump file exists.
    creates: "{{ zoidy_matecocido_dconf_begin }}"

# ======================================================================= #

# *** Make changes.

- name: Load role to Hide Desktop icons
  include_role:
    name: zoidy_matecocido
    tasks_from: background-hide_icons-go_black
    apply:
      tags:
        - background-hide_icons-go_black
  tags: background-hide_icons-go_black

- name: Load role to Fix MATE Alt-Tab slugishness
  include_role:
    name: zoidy_matecocido
    tasks_from: deprecated-fix-alt-tab-delay.yml
    apply:
      tags:
        - deprecated-fix-alt-tab-delay.yml
  tags: deprecated-fix-alt-tab-delay.yml
  # DEPRECATED/2018-12-26: Delete deprecated task file after verifying
  #   not needed. [[lb]: I..e, after setting up the other new machine.]
  when: False

# The Hack font is used by: meld-configure, and terminal-configure.
# (And preffered by Dubs Vim <https://github.com/landonb/dubs-vim>.)
- name: Load role to Install Font “Hack”
  include_role:
    name: zoidy_matecocido
    tasks_from: font-hack
    apply:
      tags:
        - font-hack
        - meld-configure
        - terminal-configure
  tags: font-hack, meld-configure, terminal-configure

- name: Load role to Customize MATE Key Bindings
  include_role:
    name: zoidy_matecocido
    tasks_from: keybinding-circus
    apply:
      tags:
        - keybinding-circus
        - reset-keybindings
  tags: keybinding-circus, reset-keybindings

- name: Load role to Customize MATE Appearance
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-appearance-configure
    apply:
      tags:
        - mate-appearance-configure
  tags: mate-appearance-configure

- name: Load role to Customize MATE Menu
  include_role:
    name: zoidy_matecocido
    tasks_from: mate-main-menu-customize
    apply:
      tags:
        - mate-main-menu-customize
  tags: mate-main-menu-customize

- name: Load role to Configure Meld Preferences
  include_role:
    name: zoidy_matecocido
    tasks_from: meld-configure
    apply:
      tags:
        - meld-configure
  tags: meld-configure

# ***

- name: Determine if host is “Desktop” or “Laptop”
  # (lb): Response should be either "Desktop" or "Notebook", at least what I've seen.
  shell: dmidecode --string chassis-type
  become: yes
  register: chassis_type
  tags: power-management-prefs-laptop

# (lb): It does not hurt to configure these setting on a Desktop,
# but for completeness, we'll restrict this task to Laptop hosts.
- name: Load role to Fiddle About Laptop Power Settings
  include_role:
    name: zoidy_matecocido
    tasks_from: power-management-prefs-laptop
    apply:
      tags:
        - power-management-prefs-laptop
  tags: power-management-prefs-laptop
  when: chassis_type.stdout == 'Notebook'

# ***

- name: Load role to Disable screensaver, and its lock
  include_role:
    name: zoidy_matecocido
    tasks_from: screensaver-tweak
    apply:
      tags:
        - screensaver-tweak
  tags: screensaver-tweak

- name: Load role to Configure mate-terminal
  include_role:
    name: zoidy_matecocido
    tasks_from: terminal-configure
    apply:
      tags:
        - terminal-configure
  tags: terminal-configure

# ======================================================================= #

# *** Record final states.

- name: Record final gsettings
  shell: "dbus-launch gsettings list-recursively | sort > {{ zoidy_matecocido_gesttings_dated }}"

- name: Record final dconf
  shell: "dbus-launch dconf dump / > {{ zoidy_matecocido_dconf_dated }}"

