---

# Avoid error: `Python module psutil is required on managed machine`.
# Install psutil for Ansible dconf module.
- name: 'Install Python development packages'
  become: true
  apt: name={{ item }}
  loop:
    - python-psutil
    - python3-psutil

