---

# Install psutil for Ansible dconf module.
# - Avoids error: `Python module psutil is required on managed machine`.
- name: 'Install Python development packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - python3-psutil

