---

# Avoid error: `Python module psutil is required on managed machine`.
# Install psutil for Ansible dconf module.
- name: 'Install Python development packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # - python-psutil
    # 2023-04-20: Already installed on Ubuntu 22.04/Linux Mint 21.2.
    - python3-psutil

