---

# 2017-07-13: Alt-tab is very slow -- there's a secondish delay.
#   Seems to be caused by "Compositing" in the Window Manager.
#
# https://askubuntu.com/questions/43875/how-do-i-adjust-the-alt-tab-speed
#
# Default (see also: Mint Menu > Preferences > Desktop Settings > Windows > Window Manger)
#   $ gsettings get com.linuxmint.desktop mate-window-manager
#   'marco-composite'
#
# 2017-07-19: Aha! I was wondering why this wasn't a problem at home:
#   on 12.04, there's a checkbox for "Use compositing" that's unchecked,
#   and Marco and Compwiz are the only two window managers
#   (so there's no marco-composite and marco-compton).
#
# So in 14.04, compositing was added to the window manager option
#   as a bundled option, in a sense (though not sure what "compton"
#   means -- is it just non-compositing, or is it something more?).

# FIXME/2019-01-22: I disabled compositing via
#   MATE Menu > Desktop Settings > Windows [tab] > Window Manager > Manager [drop]
# and changed "Marco + Compositing" to "Marco"
# but I don't see a change in gsettings, which
# still says 'marco-composite'.
# What am I missing?
- fail: msg="DISABLED: FIXME: Broke until fixed."

- name: Fix MATE Alt-Tab slugishness
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # The default mate-window-manager is 'marco-composite'.
    - schema: com.linuxmint.desktop
      key: mate-window-manager
      # Default:
      #  val: 'marco-composite'
      val: 'marco-compton'

