---

# USAGE: Task downloads and installs Hack Nerd font from GitHub release archive.

# ***

# *** Nerd Font verion -- perhaps includes latest emojis? At least include Font Awesome.

# https://github.com/ryanoasis/nerd-fonts
# https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
#
# 2022-09-15 11:23:
# https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
# https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack
# https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip

# To list fonts: fc-list

# 2020-03-19: I tested. I see 2018's 🦟 mosquito... I don't see 2019 emoji...
# same support as Hack.
# - And how do I even know that Unicode characters are coming from Hack?
#   Is there a fallback font? I don't really know how fonts work, and
#   where the OS pulls emoji characters from.

- set_fact:
    # 2022-09-21:
    #  HACK_NERD_FONT_VERS: 'v2.2.2'
    # 2023-04-25:
    HACK_NERD_FONT_VERS: 'v2.3.3'
    HACK_NERD_FONT_FILE: 'Hack'
    # 2022-09-15: If you want to install another font, e.g., Noto,
    # just change the name, e.g.:
    #  HACK_NERD_FONT_FILE: 'Noto'

# *** Alert user if newer version.

- name: 'Test if ‘jq’ is available'
  ansible.builtin.shell: "command -v jq"
  register: is_jq_avail_raw

# Note that this requires sudo/-K if `jq` not installed, but so does the
# 'Build font information cache files' handler, so you're probably running
# this task file with privileges.
- name: 'Ensure ‘jq’ is available'
  become: true
  ansible.builtin.apt: name=jq
  when: is_jq_avail_raw.failed

- name: Check for new version of Hack.
  ansible.builtin.shell: "curl -s https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest | jq -r '.tag_name'"
  register: LATEST_VERSION

- debug: msg="Latest HACK NERD FONT∷ {{ LATEST_VERSION.stdout }}"

- fail: msg="Update HACK NERD FONT! / Latest∷ {{ LATEST_VERSION.stdout }} / Current∷ {{ HACK_NERD_FONT_VERS }}"
  when: HACK_NERD_FONT_VERS != LATEST_VERSION.stdout

# *** Do the work.

- name: Ensure ~/.downloads directory exists
  file: path={{ zoidy_homefries_downloads_dir }} state=directory

- name: Fetch the Hack Nerd Font font release
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ HACK_NERD_FONT_VERS }}/{{ HACK_NERD_FONT_FILE }}.zip"
    dest: "{{ zoidy_homefries_downloads_dir }}/"

- name: Ensure user home font directory directory exists
  file: path="{{ ansible_env.HOME }}/.fonts/{{ HACK_NERD_FONT_FILE }}/" state=directory

- name: Unarchive the Hack Nerd Font font release archive (Install Font- HACK NERD FONT!)
  unarchive:
    remote_src: yes
    src: "{{ zoidy_homefries_downloads_dir }}/{{ HACK_NERD_FONT_FILE }}.zip"
    dest: "{{ ansible_env.HOME }}/.fonts/{{ HACK_NERD_FONT_FILE }}/"
  notify: Build font information cache files

