---

# Ensure ~/.local/bin/bash exists, which the keybindings use rather than,
# e.g., /bin/bash. This is useful if you want to use a custom Bash.
- name: Stat ~/.local/bin/bash
  ansible.builtin.stat: path="{{ ansible_env.HOME }}/.local/bin/bash"
  register: local_bin_bash_f

- name: Symlink ~/.local/bin/bash if not exists
  ansible.builtin.file:
    src: "/bin/bash"
    dest: "{{ ansible_env.HOME }}/.local/bin/bash"
    state: link
  when: not local_bin_bash_f.stat.exists

# ***

# Reset keybindings to their default state: absent.
- name: Clear Existing MATE Key Bindings
  ansible.builtin.shell: dconf reset -f /org/mate/desktop/keybindings/

- name: Customize MATE Key Bindings
  # debug:
  #   msg: "{{ index }} -- {{ item.name }} / {{ item.binding }} / {{ item.action }}"
  ansible.builtin.shell: |
    dconf write /org/mate/desktop/keybindings/custom{{ index }}/name "{{ item.name }}" ; \
    dconf write /org/mate/desktop/keybindings/custom{{ index }}/binding "{{ item.binding }}" ; \
    dconf write /org/mate/desktop/keybindings/custom{{ index }}/action "{{ item.action }}" ; \
  loop: "{{
    []
    + zoidy_matecocido_keybindings_basic
    + zoidy_matecocido_keybindings_bonus
    + zoidy_matecocido_keybindings_gvims
      | to_gvim_keybinding_action(zoidy_matecocido_gvim_servername, ansible_env.HOME)
  }}"
  loop_control:
    index_var: index

