---

# Main task: Check if tasks yet run, and run (via include-role) those not.

# dconf ref:
#
#   https://wiki.gnome.org/action/show/Projects/dconf
#
#   https://wiki.gnome.org/Projects/dconf/SystemAdministrators

- name: Load tasks dispatcher for ‘zoidy_matecocido’
  ansible.builtin.include_role:
    name: zoidy_matecocido
    tasks_from: all
  tags:
    - alt-tab-alt-q-to-go-backward
    - alt-tab-eliminate-delay
    - ansible-ensure-dconf
    - background-hide_icons-go_black
    - font-hack-nerd-font
    - keybinding-circus
    - reset-keybindings
    - mate-appearance-configure
    - mate-caja-preferences
    - mate-main-menu-customize
    - mate-marco-window-keybindings
    - mate-marco-window-keybindings-numpad
    - mate-media-handling
    - power-management-prefs-laptop
    - screensaver-tweak
    - screenshot-configure
    - terminal-configure

