---

# Main task: Check if tasks yet run, and run (via include-role) those not.

# dconf ref:
#
#   https://wiki.gnome.org/action/show/Projects/dconf
#
#   https://wiki.gnome.org/Projects/dconf/SystemAdministrators

- name: Load Role to Load Roles to Customize MATE, and Tweak Application dconf
  include_role:
    name: zoidy_matecocido
    tasks_from: customize
  tags:
    - background-hide_icons-go_black
    - key-bindings-fix-alt-tab-delay
    - key-bindings-rewire-hot-key
    - mate-appearance-configure
    - mate-main-menu-custom-icon
    - power-management-prefs-laptop
    - screensaver-tweak
    - terminal-configure

