---

- name: Set MATE Marco Keyboard Shortcuts
  shell: gsettings set org.mate.Marco.window-keybindings {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Keyboard Shortcuts

    # Tile window to north-east (top right) corner: Shift+Ctrl+Mod4+Page Up (keypad 9)
    - key: tile-to-corner-ne
      val: "'<Primary><Shift><Mod4>KP_Page_Up'"
    # Tile window to north-west (top left) corner: Shift+Ctrl+Mod4+Home (keypad 7)
    - key: tile-to-corner-nw
      val: "'<Primary><Shift><Mod4>KP_Home'"
    # Tile window to south-east (bottom right) corner: Shift+Ctrl+Mod4+Page Down (keypad 3)
    - key: tile-to-corner-se
      val: "'<Primary><Shift><Mod4>KP_Next'"
    # Tile window to south-west (bottom left) corner: Shift+Ctrl+Mod4+End (keypad 1)
    - key: tile-to-corner-sw
      val: "'<Primary><Shift><Mod4>KP_End'"

    # Tile window to east (right) side of screen: Shift+Ctrl+Mod4+Right
    - key: tile-to-side-e
      val: "'<Primary><Shift><Mod4>Right'"
    # Tile window to west (left) side of screen: Shift+Ctrl+Mod4+Left
    - key: tile-to-side-w
      val: "'<Primary><Shift><Mod4>Left'"

    # Move window to center of screen: Shift+Ctrl+Mod4+Begin (keypad 5)
    - key: move-to-center
      val: "'<Primary><Shift><Mod4>KP_Begin'"
    # Move window to east (right) side of screen: Shift+Ctrl+Mod4+Right (keypad 6)
    - key: move-to-side-e
      val: "'<Primary><Shift><Mod4>KP_Right'"
    # Move window to north (top) side of screen: Shift+Ctrl+Mod4+Up (keypad 8)
    - key: move-to-side-n
      val: "'<Primary><Shift><Mod4>KP_Up'"
    # Move window to south (bottom) side of screen: Shift+Ctrl+Mod4+Down (keypad 2)
    - key: move-to-side-s
      val: "'<Primary><Shift><Mod4>KP_Down'"
    # Move window to west (left) side of screen: Shift+Ctrl+Mod4+Left (keypad 4)
    - key: move-to-side-w
      val: "'<Primary><Shift><Mod4>KP_Left'"

    # 2021-01-30: I only just now added this task to setup Keyboard Shortcuts,
    # which makes me think I had not yet customized any of these settings until
    # today. But that also surprises me. So here's the list of settings not
    # set above but that gsettings indicates:
    #
    #   $ gsettings list-recursively org.mate.Marco.window-keybindings | sort
    #   activate-window-menu '<Alt>space'
    #   begin-move '<Alt>F7'
    #   begin-resize '<Alt>F8'
    #   close '<Alt>F4'
    #   lower 'disabled'
    #   maximize 'disabled'
    #   maximize-horizontally 'disabled'
    #   maximize-vertically 'disabled'
    #   minimize '<Alt>F9'
    #   move-to-corner-ne 'disabled'
    #   move-to-corner-nw 'disabled'
    #   move-to-corner-se 'disabled'
    #   move-to-corner-sw 'disabled'
    #   move-to-monitor-e 'disabled'
    #   move-to-monitor-n 'disabled'
    #   move-to-monitor-s 'disabled'
    #   move-to-monitor-w 'disabled'
    #   move-to-workspace-10 'disabled'
    #   move-to-workspace-11 'disabled'
    #   move-to-workspace-12 'disabled'
    #   move-to-workspace-1 'disabled'
    #   move-to-workspace-2 'disabled'
    #   move-to-workspace-3 'disabled'
    #   move-to-workspace-4 'disabled'
    #   move-to-workspace-5 'disabled'
    #   move-to-workspace-6 'disabled'
    #   move-to-workspace-7 'disabled'
    #   move-to-workspace-8 'disabled'
    #   move-to-workspace-9 'disabled'
    #   move-to-workspace-down '<Control><Shift><Alt>Down'
    #   move-to-workspace-left '<Control><Shift><Alt>Left'
    #   move-to-workspace-right '<Control><Shift><Alt>Right'
    #   move-to-workspace-up '<Control><Shift><Alt>Up'
    #   raise 'disabled'
    #   raise-or-lower 'disabled'
    #   toggle-above 'disabled'
    #   toggle-fullscreen 'disabled'
    #   toggle-maximized '<Alt>F10'
    #   toggle-on-all-workspaces 'disabled'
    #   toggle-shaded 'disabled'
    #   unmaximize '<Alt>F5'

