---

- name: Fiddle MATE Appearance, Look of the Desktop
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Power Management Preferences

    # Under dconf as /org/mate/desktop/interface, but
    # under gsettings as org.mate.interface
    - schema: org.mate.interface
      key: icon-theme
      val: "Mint-Y"

    - schema: org.mate.interface
      key: gtk-theme
      val: "Mint-Y-Darker"

    # Change from too-bright white border (e.g., window titlebar) to darker.
    # - With green close button circle-x (see also Mint-Y-Dark-Aqua, etc.).
    - schema: org.mate.Marco.general
      key: theme
      val: "Mint-Y-Dark-Pink"

    # WEIRD/2020-03-09 12:04: I changed another value to 'Mint-Y-Dark-Pink' at
    # Mint MENU > Appearance Preferences > Customize Theme > Window Border, but
    # I cannot find the corresponding key in neither gsettings nor dconf, nor
    # under ~/.config/. Oh, well, maybe it was a holder from the 19.1 → 19.3
    # upgrade? In any case, just be aware on next distro install:
    # - HINT: If mate-terminal has no border (which makes it hard to tell where
    # one window ends and another begins; and just looks bad in general), then
    # open Appearances from the Mint MATE menu, and customize the Window Border.

- name: Fiddle MATE Appearance, Notifications
  ansible.builtin.shell: dconf write {{ item.key }} {{ item.val }}
  loop:

    # The 'coco' notification theme does not look good with Mint-Y.
    - key: "/org/mate/notification-daemon/theme"
      val: '"''slider''"'

    # Leave default:
    #   - key: /org/mate/notification-daemon/popup-location
    #     val: "'top_right'"

