---

- name: Customize MATE Appearance window look and feel
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Preferences > Appearance > Custom > Customize...

    # Schema is under dconf as /org/mate/desktop/interface,
    # and also under gsettings as org.mate.interface.
    #
    # dconf:
    #
    #   [org/mate/desktop/interface]
    #   gtk-theme='Mint-Y-Dark'
    #   icon-theme='Mint-Y-Dark'
    #
    #   [org/mate/desktop/peripherals/mouse]
    #   cursor-theme='Bibata-Modern-Ice'
    #
    # gsettings:
    #
    #   org.mate.interface gtk-theme 'Mint-Y-Dark'
    #   org.mate.interface icon-theme 'Mint-Y-Dark'
    #   org.mate.peripherals-mouse cursor-theme 'Bibata-Modern-Ice'

    # MATE Menu > Preferences > Appearance > Custom > Customize... > Controls
    - schema: org.mate.interface
      key: gtk-theme
      val: "Mint-Y-Dark"

    # MATE Menu > Preferences > Appearance > Custom > Customize... > Window Border
    #
    # ISOFF/2023-04-21: Don't set the default value, in case Mint changes
    # default in the future, so you can demo new default.
    #
    # - schema: org.mate.Marco.general
    #   key: theme
    #   # 2023-04-21: The default.
    #   val: "Mint-Y"

    # MATE Menu > Preferences > Appearance > Custom > Customize... > Icons
    - schema: org.mate.interface
      key: icon-theme
      val: "Mint-Y-Dark"

    # MATE Menu > Preferences > Appearance > Custom > Customize... > Pointer
    #
    # ISOFF/2023-04-21: Don't set the default value, in case Mint changes
    # default in the future, so you can demo new default.
    #
    # - schema: org.mate.peripherals-mouse
    #   key: cursor-theme
    #   # 2023-04-21: The default. Whodda thought I'd enjoy a new cursor design.
    #   val: "Bibata-Modern-Classic"

# ***

- name: Customize MATE notifications theme
  ansible.builtin.shell: dconf write {{ item.key }} {{ item.val }}
  loop:

    # The 'coco' notification theme does not look good with Mint-Y.
    - key: "/org/mate/notification-daemon/theme"
      val: '"''slider''"'

    # Leave default:
    #   - key: /org/mate/notification-daemon/popup-location
    #     val: "'top_right'"

  # IZOFF/2023-04-20 19:07: Disabled. I like the 'coco' theme.
  when: False

