---

- name: Form MATE menu icon target path
  set_fact:
    zoidy_matecocido_mate_menu_icon_dst: "{{ zoidy_matecocido_config_dir }}/mate-menu-icon_{{ zoidy_matecocido_mate_menu_icon_24x | basename }}"

- name: Ensure zoidy pooh config directory exists
  file: path={{ zoidy_matecocido_config_dir }} state=directory
  tags: always

- name: Copy MATE menu icon image to user home zoidy pooh config directory
  copy:
    src: "{{ zoidy_matecocido_mate_menu_icon_24x }}"
    dest: "{{ zoidy_matecocido_mate_menu_icon_dst }}"

- name: Stylize Mint Menu (in lower-left of MATE)
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    - schema: com.linuxmint.mintmenu
      key: applet-icon
      val: "'{{ zoidy_matecocido_mate_menu_icon_dst }}'"

    - schema: com.linuxmint.mintmenu
      key: hide-applet-icon
      val: "false"

    - schema: com.linuxmint.mintmenu
      key: applet-text
      val: "''"

