---

- name: Configure MATE caja application (basic)
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # caja > Edit > Preference > File Management Preferences

    - schema: org.mate.caja.preferences
      key: default-folder-viewer
      # Default default-folder-viewer 'icon-view'
      val: "'list-view'"

    - schema: org.mate.caja.preferences
      key: show-hidden-files
      val: "true"

- name: Configure MATE caja application (advanced)
  ansible.builtin.shell: dconf write {{ item.key }} {{ item.val }}
  loop:

    - key: "/org/mate/caja/window-state/start-with-location-bar"
      val: "true"

