---

- name: Configure MATE caja application — dconf settings
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # caja > Edit > Preference > File Management Preferences

    - schema: org.mate.caja.preferences
      key: default-folder-viewer
      # Default: "'icon-view'"
      val: "'list-view'"

    - schema: org.mate.caja.preferences
      key: show-hidden-files
      # Default: "false"
      val: "true"

    # See also dconf option:
    #   dconf read /org/mate/caja/preferences/always-use-location-entry
    - schema: org.mate.caja.preferences
      key: always-use-location-entry
      # Default: "false"
      val: "true"

