---

- name: Fiddle MATE Appearance, Look of the Desktop
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Power Management Preferences

    # Under dconf as /org/mate/desktop/interface, but
    # under gsettings as org.mate.interface
    - schema: org.mate.interface
      key: icon-theme
      val: "Mint-Y"

    - schema: org.mate.interface
      key: gtk-theme
      val: "Mint-Y-Darker"

    # Change from too-bright white border (e.g., window titlebar) to darker.
    # - With green close button circle-x (see also Mint-Y-Dark-Aqua, etc.).
    - schema: org.mate.Marco.general
      key: theme
      val: "Mint-Y-Dark-Pink"

- name: Fiddle MATE Appearance, Notifications
  shell: dconf write {{ item.key }} {{ item.val }}
  loop:

    # The 'coco' notification theme does not look good with Mint-Y.
    - key: "/org/mate/notification-daemon/theme"
      val: '"''slider''"'

    # Leave default:
    #   - key: /org/mate/notification-daemon/popup-location
    #     val: "'top_right'"

