---

# E.g., ~/.config/zoidy_matecocido/mate-menu-icon_triple-face-pips_21x21.png
- name: Form MATE menu icon target path
  set_fact:
    zoidy_matecocido_mate_menu_icon_dst: "{{ zoidy_matecocido_config_dir }}/mate-menu-icon_{{ zoidy_matecocido_mate_menu_icon_22x | basename }}"

# E.g., mkdir -p ~/.config/zoidy_matecocido
- name: Ensure zoidy_matecocido config directory exists
  file: path={{ zoidy_matecocido_config_dir }} state=directory
  tags: always

# Copies, e.g., ~/.zoidy/assets/mate-menu-knucklebones/triple-face-pips_21x21.png
- name: Copy MATE menu icon image to user home application config directory
  copy:
    src: "{{ zoidy_matecocido_mate_menu_icon_22x }}"
    dest: "{{ zoidy_matecocido_mate_menu_icon_dst }}"

- name: Stylize Mint MATE Menu (in lower-left of panel)
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # Default Linux Mint 21.1: applet-icon "'linuxmint-logo-ring-symbolic'"
    # - Def't Linux Mint 19.3: applet-icon "'linuxmint-logo-filled-ring'"
    - schema: com.linuxmint.mintmenu
      key: applet-icon
      val: "'{{ zoidy_matecocido_mate_menu_icon_dst }}'"

    # Default: applet-icon-size '22'
    # 
    #  - schema: com.linuxmint.mintmenu
    #    key: applet-icon-size
    #    val: "22"

    # Default Linux Mint 21.1: applet-text "''"
    # - But on hover shows "Linux Mint 21.1 Vera"
    #   - Oh, huh, this setting affects the text to the right of the icon
    #     in the panel. It doesn't change the popup text.
    # - Def't Linux Mint 19.3: applet-text "'Menu'"
    #
    #  - schema: com.linuxmint.mintmenu
    #    key: applet-text
    #    val: "''"

    # As seen on Linux Mint 19.3, but not Linux Mint 21.1.
    #  gsettings get com.linuxmint.mintmenu custom-color          # "'#DEDEDE'"
    #  gsettings get com.linuxmint.mintmenu custom-heading-color  # "'#3C3C3C'"

    # Default Linux Mint 21.1: default-applet-icon "'linuxmint-logo-ring-symbolic'"
    # - Def't Linux Mint 19.3: default-applet-icon "'linuxmint-logo-filled-ring'"
    # 
    #   - schema: com.linuxmint.mintmenu
    #     key: default-applet-icon
    #     val: "'linuxmint-logo-filled-ring'"

    # *** Make Mint MATE Menu Hot Key Harder to AcciDentPress
    # The default mapping to open the MATE Menu is the Windows/Super key
    # ('<Super>'), but I often accidentally press Super when I don't intend
    # to do so, so disabling.
    # - 2023-04-21: I previously set this to "'<Super>Shift_L'", but I've
    #   since nabbed that keybinding for a global hotkey — but I didn't
    #   even notice that I had shadowed this binding. Which probably
    #   means I don't ever access MATE menu via the keyboard shortcut.
    #   - Really, I rarely open the MATE menu... so don't need a binding.
    # Default: "'Shift_L'"
    # Less hot: "'<Super>Shift_L'"
    - schema: com.linuxmint.mintmenu
      key: hot-key
      val: "''"

    # Default: offset '0'
    #
    #  - schema: com.linuxmint.mintmenu
    #    key: offset
    #    val: "0"

# ***

# Tweak the MATE menu contents (remove stuff you don't use, etc.).
#
# - BWARE/2023-04-21: One drawback: This moves the "Quit" button
#   higher up, so that it's not just above the MATE menu button
#   when you click it. But rather, you now need to mouse up a
#   ways to click it.
#   - KCALM: I use a global keybinding to lock the screen,
#     and I rarely shutdown, so not gonna care. Keep calm.
#   - BWAIT: But wait, given that I don't open this menu
#     very often, maybe I'll leave the defaults so the Quit
#     button is closer by mouse to the MATE menu button you
#     clicked.

- name: Stylize Mint MATE Menu contents
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # Do not show (useless to me) list of places (caja shortcuts).
    # - This removes the Places list (Computer, Home Folder, Network, Desktop, Trash)
    #   from the top-left of the main MATE menu popup.
    #   - It also causes the popup to be shorter.
    #
    # - Default: plugins-list "\"['places', 'system_management', 'newpane', 'applications']\""
    - schema: com.linuxmint.mintmenu
      key: plugins-list
      # val: "\"['places', 'system_management', 'newpane', 'applications']\""
      val: "\"['system_management', 'newpane', 'applications']\""

    # If start-with-favorites is true, Mint MATE menu always shows
    # Favorites instead of All applications.
    # - When start-with-favorites is false, it restores previous view.
    #
    # Default: start-with-favorites "false"
    - schema: com.linuxmint.mintmenu
      key: start-with-favorites
      val: "false"

    # At some point (early Linux Mint 19.3 testing perhaps, but not recently),
    # I set a theme, not sure why: theme-name "'Mint-Y-Darker-Blue'"
    # - Default: theme-name "'default'"
    #
    #  - schema: com.linuxmint.mintmenu
    #    key: theme-name
    #    val: "'default'"

    # ***

    # CXREF:
    #   https://github.com/linuxmint/mintmenu/blob/master/usr/lib/linuxmint/mintMenu/plugins/system_management.py

    # Because we remove Places from the MATE menu, as well as
    # Package Manager and Software manager from the System
    # section (both on the left side of the MATE menu), it
    # decreases the popup height.
    # - Here we set a height so that the "All applications"
    #   Applications list shows up without a scroll bar.
    #
    # Default: 180
    - schema: com.linuxmint.mintmenu.plugins.system_management
      key: height
      # val: "180"
      val: "543"

    # Per system_management.py, 'height' ignored unless 'allow-scrollbar'.
    # - Default: allow-scrollbar "'false'"
    # - DUNNO/2023-04-21: When this is false, I still see MATE menu scrollbars.
    - schema: com.linuxmint.mintmenu.plugins.system_management
      key: allow-scrollbar
      # val: "'false'"
      val: "'true'"

    # ***

    # Hide MATE menu > Package Manager option (on left, under System).
    #
    # Default: true
    - schema: com.linuxmint.mintmenu.plugins.system_management
      key: show-package-manager
      # val: "true"
      val: "false"

    # Hide MATE menu > Software Manager option (on left, under System).
    #
    # Default: true
    - schema: com.linuxmint.mintmenu.plugins.system_management
      key: show-software-manager
      # val: "true"
      val: "false"

  # ISOFF/2023-04-21: See comments above. While I appreciate a cleaner
  # (more empty) Mint menu, I also appreciate the Quit button at the
  # bottom of the left sidebar, just above the Mint menu panel button.
  when: False

