---

# USYNC:
#
#   cd ~/.kit/ansible/roles/zoidy_matecocido/tasks/
#   meld mate-marco-window-keybindings.yml mate-marco-window-keybindings-numpad.yml &

- name: Set MATE Marco Keyboard Shortcuts
  ansible.builtin.shell: gsettings set org.mate.Marco.window-keybindings {{ item.key }} {{ item.val }}
  loop:

    # CXREF: MATE Menu > Keyboard Shortcuts.

    # SAVVY: Mod4 is the Super key.

    # SAVVY: These all default to "'disabled'".

    # *** Move commands

    # Move window to east (right) side of screen: Shift+Ctrl+Mod4+Alt+Right (-Alt: tile-to-side-e)
    - key: move-to-side-e
      val: "'<Primary><Shift><Mod4><Alt>Right'"
    # Move window to north (top) side of screen: Shift+Ctrl+Mod4+Up
    - key: move-to-side-n
      val: "'<Primary><Shift><Mod4>Up'"
    # Move window to south (bottom) side of screen: Shift+Ctrl+Mod4+Down
    - key: move-to-side-s
      val: "'<Primary><Shift><Mod4>Down'"
    # Move window to west (left) side of screen: Shift+Ctrl+Mod4+Alt+Left (-Alt: tile-to-side-w)
    - key: move-to-side-w
      val: "'<Primary><Shift><Mod4><Alt>Left'"

    # Move window to center of screen: Shift+Ctrl+Mod4+.(Period(GreaterThan))
    # - Mnemonic: '>' is above '.', dot, centered.
    # - DUNNO: This doesn't always work. E.g., works after tile-corner-to-nw,
    #   but not after any of the other 3 tile-corner-to motions.
    #   - Though you'll find that unmaximize works after most commands,
    #     including tile-corner-to-*, and also centers the center (at
    #     least horizontally; if you run unmaximize after either
    #     move-to-side-n or move-to-side-s, nothing happens, and the
    #     window remains centered horizontally and still snapped
    #     vertically to the top or bottom).
    - key: move-to-center
      val: "'<Primary><Shift><Mod4>greater'"

    # *** Tile commands

    # Tile window to north-east (top right) corner: Shift+Ctrl+Mod4+PageUp
    - key: tile-to-corner-ne
      val: "'<Primary><Shift><Mod4>Page_Up'"
    # Tile window to north-west (top left) corner: Shift+Ctrl+Mod4+Home
    - key: tile-to-corner-nw
      val: "'<Primary><Shift><Mod4>Home'"
    # Tile window to south-east (bottom right) corner: Shift+Ctrl+Mod4+PageDown
    - key: tile-to-corner-se
      val: "'<Primary><Shift><Mod4>Page_Down'"
    # Tile window to south-west (bottom left) corner: Shift+Ctrl+Mod4+End
    - key: tile-to-corner-sw
      val: "'<Primary><Shift><Mod4>End'"

    # Tile window to east (right) side of screen: Shift+Ctrl+Mod4+Right
    - key: tile-to-side-e
      val: "'<Primary><Shift><Mod4>Right'"
    # Tile window to west (left) side of screen: Shift+Ctrl+Mod4+Left
    - key: tile-to-side-w
      val: "'<Primary><Shift><Mod4>Left'"
    # SAVVY: No vertical tiling, e.g., neither tile-to-side-n nor tile-to-side-s.

    # After tiling, restore previous window size and position: Ctrl-Shift-Cmd-/(ForwardSlash(QuestionMark))
    # - MATE Menu > Keyboard Shortcuts > Window Management > Restore window
    - key: unmaximize
      # Defaults:
      #   val: "'<Alt>F5'"
      val: "'<Primary><Shift><Mod4>question'"

    # *** Other window commands

    # Maximize window vertically: Shift+Ctrl+Mod4+|(BackwardSlash(Bar))
    #
    # Use Case: Use as part of a sequence to resize and center a window.
    # - Inspiration: There's a great app for Darwin (macOS), Rectangle, that
    #   exposes a bunch of window commands to which you can assign shortcuts.
    #   When I want to center and resize a window, but not quite maximize it,
    #   I use the *Almost Maximize* command (wired to Ctrl-Shift-Cmd-/),
    #   followed by a couple *Larger* commands (wired to Ctrl-Shift-Cmd-+).
    #   Why? Because I hide the macOS menubar, and hence the clock, so I
    #   use a Vim plugin that shows the clock in the titlebar (and status
    #   line). Then, when I use the browser, I make the window almost-
    #   maximized so I can see the clock in the Vim titlebar.
    # - On Mint MATE, there's not a similar such command. Well, there
    #   *appears* to be, but it doesn't work for me: There are tile-to-*
    #   commands and a move-to-center command, but when I try tile-to-side-e
    #   or tile-to-side-w and then move-to-center, the window doesn't budge!
    # - So here's the best workaround I could figure out:
    #     Tile to corner, center, maximize:
    #       Ctrl-Shift-Cmd-7 tiles to the upper left;
    #       Ctrl-Shift-Cmd-5 centers the window; and
    #       Ctrl-Shift-Cmd-/ maximizes the window height.
    #   Aka, the long way to centering a window using maximum height.
    #
    # - EVEN BETTER: No sooner did I add this mapping (and write this long
    #   comment) then I looked for a window resizer and centerer, found a
    #   decent example, and cooked up my own solution, found here:
    #     https://github.com/landonb/reputed-tiler/blob/release/bin/window-to-center
    #   I wired this as a custom binding, which you'll find in this repo at:
    #     defaults/main/keybindings.yml
    #   and which is wired to Ctrl-Shift-Cmd-KP_Add. I like the custom
    #   solution better not just because it's wired to one shortcut,
    #   but because it makes the window wider than the workaround that
    #   I documented above.
    #   - Nonetheless, I still might find that I like maximize-vertically
    #     wired to its own shortcut, so here it is.
    - key: maximize-vertically
      # Mnemonically, the bar key makes sense (it's vertical).
      val: "'<Primary><Shift><Mod4>bar'"

    # Maximize window horizontally: Shift+Ctrl+Mod4+_(Dash(Underscore))
    #
    # For parity, also because after adding maximize-vertically, I suddenly
    # wanted this one, too, for use case: viewing more columns in spreadsheet,
    # but not going fullscreen.
    - key: maximize-horizontally
      val: "'<Primary><Shift><Mod4>underscore'"

    # 2021-01-30: I only just now added this task to setup Keyboard Shortcuts,
    # which makes me think I had not yet customized any of these settings until
    # today. But that also surprises me. So here's the list of settings not
    # set above but that gsettings indicates:
    #
    #   $ gsettings list-recursively org.mate.Marco.window-keybindings | sort
    #   activate-window-menu '<Alt>space'
    #   begin-move '<Alt>F7'
    #   begin-resize '<Alt>F8'
    #   close '<Alt>F4'
    #   lower 'disabled'
    #   maximize 'disabled'
    #   maximize-horizontally 'disabled'
    #   maximize-vertically 'disabled'
    #   minimize '<Alt>F9'
    #   move-to-corner-ne 'disabled'
    #   move-to-corner-nw 'disabled'
    #   move-to-corner-se 'disabled'
    #   move-to-corner-sw 'disabled'
    #   move-to-monitor-e 'disabled'
    #   move-to-monitor-n 'disabled'
    #   move-to-monitor-s 'disabled'
    #   move-to-monitor-w 'disabled'
    #   move-to-workspace-10 'disabled'
    #   move-to-workspace-11 'disabled'
    #   move-to-workspace-12 'disabled'
    #   move-to-workspace-1 'disabled'
    #   move-to-workspace-2 'disabled'
    #   move-to-workspace-3 'disabled'
    #   move-to-workspace-4 'disabled'
    #   move-to-workspace-5 'disabled'
    #   move-to-workspace-6 'disabled'
    #   move-to-workspace-7 'disabled'
    #   move-to-workspace-8 'disabled'
    #   move-to-workspace-9 'disabled'
    #   move-to-workspace-down '<Control><Shift><Alt>Down'
    #   move-to-workspace-left '<Control><Shift><Alt>Left'
    #   move-to-workspace-right '<Control><Shift><Alt>Right'
    #   move-to-workspace-up '<Control><Shift><Alt>Up'
    #   raise 'disabled'
    #   raise-or-lower 'disabled'
    #   toggle-above 'disabled'
    #   toggle-fullscreen 'disabled'
    #   toggle-maximized '<Alt>F10'
    #   toggle-on-all-workspaces 'disabled'
    #   toggle-shaded 'disabled'

