---

# MAYBE/2018-12-24: Fiddle with style.
# ::
#
#   [org/gnome/meld]
#   style-scheme='meld-base'
#   wrap-mode='none'
#
#   gsettings:
#     org.gnome.meld style-scheme 'meld-base'
#     org.gnome.meld style-scheme 'classic'  # default

# 2019-03-13 16:28: gsettings fails if schema not present.
# But I've been running this task before/independently of
# zoidy_mintyfresh. So apt-ensure installed here, I suppose!
- name: Install Meld
  become: true
  apt: name=meld
  when: False  # See instead: zoidy_apps_et_al/tasks/app-meld.yml

- name: Configure Meld
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    - schema: org.gnome.meld
      key: use-system-font
      val: "false"

    - schema: org.gnome.meld
      key: custom-font
      val: "'Hack 10'"

    - schema: org.gnome.meld
      key: highlight-current-line
      val: "true"

    - schema: org.gnome.meld
      key: show-line-numbers
      val: "true"

    - schema: org.gnome.meld
      key: indent-width
      val: "4"

    - schema: org.gnome.meld
      key: insert-spaces-instead-of-tabs
      val: "true"

    - schema: org.gnome.meld
      key: filename-filters
      val: "\"[('Backups', true, '#*# .#* ~* *~ *.{orig,bak,swp}'), ('OS-specific metadata', true, '.DS_Store ._* .Spotlight-V100 .Trashes Thumbs.db Desktop.ini'), ('Version Control', true, '_MTN .bzr .svn .svn .hg .fslckout _FOSSIL_ .fos CVS _darcs .git .svn .osc'), ('Binaries', true, '*.{pyc,a,obj,o,so,la,lib,dll,exe}'), ('Media', false, '*.{jpg,gif,png,bmp,wav,mp3,ogg,flac,avi,mpg,xcf,xpm}'), (\\\"Nark Dobbin'\\\", true, '.make.out .tox _build htmlcov'), ('Trust Me! CI', true, '.trustme.kill .trustme.lock .trustme.log'), ('Python bytecode', true, '__pycache__ .pytest_cache *.egg-info'), ('tags', true, 'tags'), ('Python CI', true, '.coverage coverage.xml')]\""

