---

- name: Fiddle About Laptop Power Settings
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Power Management Preferences

    # On Battery Power: When battery power is critically low: Shut'er down!
    - schema: org.mate.power-manager
      key: action-critical-battery
      val: "shutdown"

    # On AC Power: When laptop lid is closed: Blank screen
    - schema: org.mate.power-manager
      key: button-lid-ac
      val: "blank"

    # On Battery Power: When laptop lid is closed: Blank screen
    - schema: org.mate.power-manager
      key: button-lid-battery
      val: "blank"

    # [lb]: When true, idle-dim-battery seems to dim screen within seconds
    # of inactivity, i.e., Way too short!
    - schema: org.mate.power-manager
      key: idle-dim-battery
      val: "false"

# MEH: We could use symlink instead, which means we could edit service
# as user (without sudo) but whatever, this script won't change often.
- name: Permanently disable wake-on-lid
  become: true
  template:
    src: laptop-lid-disable-wake.service
    dest: /etc/systemd/system

# `systemctl daemon-reload`
- name: Reload systemd configs
  become: true
  systemd:
    daemon_reload: yes

# `systemctl enable laptop-lid-disable-wake.service`
# `systemctl start laptop-lid-disable-wake.service`
- name: Start and Enable on boot Our disable wake-on-lid service
  become: true
  systemd:
    name: laptop-lid-disable-wake.service
    state: started
    enabled: yes

# Check systemctl to verify that the LID service is setup:
#
#   systemctl status laptop-lid-disable-wake.service
#
# and
#
#   cat /proc/acpi/wakeup | grep "^LID"

