---

- name: Fiddle About Laptop Power Settings
  ansible.builtin.shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # MATE Menu > Power Management Preferences

    # On Battery Power: When battery power is critically low: Shut'er down!
    - schema: org.mate.power-manager
      key: action-critical-battery
      val: "shutdown"

    # On AC Power: When laptop lid is closed: Blank screen (which locks it)
    - schema: org.mate.power-manager
      key: button-lid-ac
      # 2020-09-01: When using an external monitor, do nothing
      # when the lid is closed (don't lock the session).
      # - If you want to lock the screen when laptop lid is closed,
      #   "blank" the screen instead:
      #     val: "blank"
      # MAYBE/2023-04-21: Make this settable from group_vars, possibly
      #                   tied to ansible_hostname.
      val: "nothing"

    # On Battery Power: When laptop lid is closed: Blank screen.
    # - Note that the screen should still turn off, but session
    #   won't be locked.
    - schema: org.mate.power-manager
      key: button-lid-battery
      val: "blank"

    # [lb]: When true, idle-dim-battery seems to dim screen within seconds
    # of inactivity, i.e., Way too short!
    - schema: org.mate.power-manager
      key: idle-dim-battery
      val: "false"

