---

- name: Make Mint MATE Menu Hot Key Harder to AcciDentPress
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    # The default mapping to open the MATE Menu is the Windows/Super key
    # ('<Super>'), but I fat-finger it sometimes when I don't mean to so
    # add the shift key.
    - schema: com.linuxmint.mintmenu
      key: hot-key
      val: "'<Super>Shift_L'"

