---

- name: Disable MATE Screensaver, and Its Lock
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    - schema: org.mate.screensaver
      key: idle-activation-enabled
      val: "true"

    - schema: org.mate.screensaver
      key: lock-enabled
      val: "false"

    - schema: org.mate.screensaver
      key: themes
      val: '"[''screensavers-gleidescope'']"'

    - schema: org.mate.screensaver
      key: mode
      val: "'single'"

