---

- name: Form MATE desktop background target path
  set_fact:
    zoidy_matecocido_desktop_backgd_dst: "{{ zoidy_matecocido_config_dir }}/mate-dtop-bkgd_{{ zoidy_matecocido_desktop_background | basename }}"

- name: Ensure zoidy_matecocido config directory exists
  file: path={{ zoidy_matecocido_config_dir }} state=directory
  tags: always

- name: Copy lock screen background image to user home config application directory
  copy:
    src: "{{ zoidy_matecocido_desktop_background }}"
    dest: "{{ zoidy_matecocido_desktop_backgd_dst }}"

- name: Disable MATE Screensaver, and Its Lock, and Set Lock Screen Background
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.val }}
  loop:

    - schema: org.mate.screensaver
      key: idle-activation-enabled
      val: "true"

    - schema: org.mate.screensaver
      key: lock-enabled
      val: "false"

    - schema: org.mate.screensaver
      key: themes
      val: '"[''screensavers-gleidescope'']"'

    - schema: org.mate.screensaver
      key: mode
      val: "'single'"

    # Because we disable lock-on-screensaver, we provide manual method,
    #   gnome-screensaver-command --lock
    # but that uses its own background, which defaults to Mint logo.
    - schema: org.gnome.desktop.background
      key: picture-uri
      # NOTE: The file:// prefix is mandatory.
      val: "'file://{{ zoidy_matecocido_desktop_backgd_dst }}'"

