---

- name: Configure MATE-Terminal Profile Preferences
  dconf:
    key: "/org/mate/terminal/profiles/default/{{ item.key }}"
    value: "{{ item.val }}"
    state: present
  loop:

    - key: "use-theme-colors"
      val: "false"

    - key: "default-show-menubar"
      val: "false"

    - key: "foreground-color"
      val: "'#FFFFFFFFFFFF'"

    # Default: background-darkness=0.90000000000000002
    - key: "background-darkness"
      val: "1.0"

    # Default: background-type='transparent'
    - key: "background-type"
      val: "'solid'"

    # Default: background-color='#FFFFFFFFDDDD'
    - key: "background-color"
      val: "'#000000000000'"

    - key: "use-system-font"
      val: "false"

    - key: "font"
      val: "'Hack 10'"

    # Other values whose defaults work without being twiddled:
    #
    #   - key: "visible-name"
    #         val: "'Default'"
    #
    #       - key: "palette"
    #         val: "'#2E2E34343636:#CCCC00000000:#4E4E9A9A0606:#C4C4A0A00000:#34346565A4A4:#757550507B7B:#060698209A9A:#D3D3D7D7CFCF:#555557575353:#EFEF29292929:#8A8AE2E23434:#FCFCE9E94F4F:#72729F9FCFCF:#ADAD7F7FA8A8:#3434E2E2E2E2:#EEEEEEEEECEC'"
    #
    #       - key: "silent-bell"
    #         val: "true"
    #
    #       - key: "scrollback-unlimited"
    #         val: "true"
    #
    #       - key: "bold-color"
    #         val: "'#000000000000'"


- debug: msg="NOTE! You must logon again for changes to take effect!"

