---

- name: Configure MATE-Terminal Profile Preferences
  community.general.dconf:
    key: "/org/mate/terminal/profiles/default/{{ item.key }}"
    value: "{{ item.val }}"
    state: present
  loop:

    # *** White on black theme.

    # Note when you go through the GUI, you'll use the color picker,
    # and you'll also see this change in the conf:
    #
    #   [org/gtk/settings/color-chooser]
    #   selected-color=(true, 0.0, 0.0, 0.0, 1.0)
    #
    #     →
    #
    #   custom-colors=[(1.0, 1.0, 0.8666666666666667, 1.0)]
    #   selected-color=(true, 1.0, 1.0, 1.0, 1.0)

    # - CXREF: mate-terminal > Edit > Colors > Background color
    - key: "background-color"
      # Default: "'#FFFFFFFFDDDD'"    
      val: "'#000000000000'"

    # - CXREF: mate-terminal > Edit > Colors > Text color
    - key: "foreground-color"
      # Default: "'#000000000000'"    
      val: "'#FFFFFFFFFFFF'"

    # - CXREF: mate-terminal > Edit > Colors > ✗ Use colors from system theme
    - key: "use-theme-colors"
      # Defaults enabled, but no setting.
      val: "false"

    # No longer necessary in Linux Mint 21.1:
    #
    #  - key: "background-darkness"
    #    # Default: absent.
    #    val: "1.0"

    # Circa 2019/Linux Mint 19.3, defaults "'transparent'";
    # in Linux Mint 21.1 defaults "'solid'" but this setting
    # absent.
    #
    #  - key: "background-type"
    #    val: "'solid'"

    # *** Hack font

    # Default "Monospace Regular 12", but no setting.
    # - CXREF: mate-terminal > Edit > General > Font
    - key: "font"
      # Default: absent.
      # - See also:
      #     val: "'Hack 10'"
      val: "'Hack Nerd Font 10'"

    # - CXREF: mate-terminal > Edit > General > ✗ Use the system fixed width font
    - key: "use-system-font"
      # Default: absent.
      val: "false"

    # *** Other settings

    # Defaults enabled, but no setting.
    # - CXREF: mate-terminal > Edit > Profile Preferences > General
    #            > ✗ Show menubar by default in new terminals
    - key: "default-show-menubar"
      # Default: absent.
      val: "false"

    # *** ISOFF: Hide scrollbar

    # Defaults enabled, but Linux Mint 21.1 scrollbars are less distracting
    # than they were (to me) in Linux Mint 19.3. So no longer hiding.
    # - CXREF: mate-terminal > Edit > Scrolling > Scrollbar is: ✓ Disabled
    #
    #  - key: "scrollbar-position"
    #    # Default: absent.
    #    val: "hidden"

# mate-terminal loads GUI settings changes immediately, but not backdoor
# dconf updates.
- debug:
    msg: "CHORE: You must exit all terminals to effectualize mate-terminal changes"

# *** Configure keyboard shortcuts

# CXREF: mate-terminal > Edit > Keyboard Shortcuts...

# CPYST: Use dconf-reset to revert to defaults.
#
#   dconf reset /org/mate/terminal/keybindings/<key>
#
# In Linux Mint 21.1, /org/mate/terminal/keybindings/ is absent by default,
# so you could also reset the whole directory:
#
#   dconf reset -f /org/mate/terminal/keybindings/

# KLUGE/2023-04-22: There's a regression in dconf v6.5.0. Avoid it:
#
#   ansible-galaxy collection install 'community.general:!=6.5.0'
#
# CXREF:
#
#   https://github.com/ansible-collections/community.general/commit/a5765143f1b172396749f8ab54a466b8f3e2be74

- name: Configure MATE-Terminal Keyboard Shortcuts
  community.general.dconf:
    key: "/org/mate/terminal/keybindings/{{ item.key }}"
    value: "{{ item.val }}"
    state: present
  loop:

    # *** GUI shows 2 [✓] checkbox options atop the keys list

    # [✓] Enable menu access keys (such as Alt+F to open the File menu)
    #
    #     /org/mate/terminal/global/use-mnemonics=true
    #
    # (lb): I don't use Alt-f from terminal.
    # - And it's not a readline binding.
    # - So it's fine to leave this enabled (though I never use it,
    #   because I don't use the mate-terminal menu bar in normal
    #   usage (only when hacking on this Ansible task); and this
    #   binding is a no-op when menubar is hidden, anyway).

    # [✓] Enable the menu shortcut key (F10 by default)
    #
    #     /org/mate/terminal/global/use-menu-accelerators=true
    #
    # (lb): Pressing <F10> has same effect has Alt-f: Expands the File menu.
    # - Ha! I didn't know this until 2020-02-11-today: Same effect in GVim!
    # - So pressing F10 is a convention, to appease keyboarders whom lack an
    #   Alt key, perhaps (much like pressing ESC is a convention for starting
    #   an Alt-key press without using the Alt key).
    # - 2023-04-22: When menubar is hidden, F10 sends '~' character.

    # *** Keyboard Shortcuts > Shortcut keys

    # This is an exhaustive list of *all the bindings*.

    # **** Shortcut keys > Edit

    # Copy, Paste, and Select All are currently keepers.
    # - I use these still — brainy still wired this way.

    # # "Copy"
    # # Default: Shift+Ctrl+C
    # - key: "copy"
    #   val: "'<Primary><Shift>c'"

    # # "Paste"
    # # Default: Shift+Ctrl+V
    # - key: "paste"
    #   val: "'<Primary><Shift>v'"

    # # "Select All"
    # # Default: Shift+Ctrl+A
    # - key: "select-all"
    #   val: "'<Primary><Shift>a'"

    # **** Shortcut keys > File

    # "Close Tab"
    # Default: Shift+Ctrl+W
    - key: "close-tab"
      val: "'disable'"

    # (lb): I use this! It's a quick way to close the window!
    # - Especially because I disabled Ctrl-d exit from term.
    #
    # # "Close Window"
    # # Default: Shift+Ctrl+Q
    # - key: "close-window"
    #   val: "'<Primary><Shift>q'"

    # # "New Profile"
    # # Default: disabled
    # - key: "new-profile"
    #   val: "'disabled'"

    # "New Tab"
    # Default: Shift+Ctrl+T
    - key: "new-tab"
      val: "'disabled'"

    # (lb): 2020-02-11: Leave this'un?
    # - 2023-04-22: I don't use it (I usually use a global <Cmd-m> keybinding
    #   instead), but the binding also doesn't conflict with anything... then
    #   again, if disable it, you could know for sure whether you use it or not.
    #
    # # "New Window"
    # # Default: Shift+Ctrl+N
    # - key: "new-window"
    #   # val: "'<Primary><Shift>n'"
    #   val: "'disabled'"

    # **** Shortcut keys > Help

    # (lb): Fairly helpless.
    #
    # "Contents"
    # Default: F1
    - key: "help"
      val: "'disabled'"

    # **** Shortcut keys > Search

    # (lb): I'm torn on these -- part of me wants to disable these,
    # because I should be using tmux buffer search! But I don't *always*
    # tmux, though I'm leaning more-so towards always tmuxxing recently.
    # So, I dunno, let's disable the Find bindings; I so rarely use 'em,
    # and you can search from the mate-terminal menubar if you must.

    # "Find"
    # Default: Shift+Ctrl+F
    - key: "search-find"
      val: "'disabled'"

    # "Find Next"
    # Default: Shift+Ctrl+H
    - key: "search-find-next"
      val: "'disabled'"

    # "Find Previous"
    # Default: Shift+Ctrl+G
    - key: "search-find-previous"
      val: "'disabled'"

    # **** Shortcut keys > Tabs

    # # "Detach Tab"
    # # Default: disabled
    # - key: "detach-tab"
    #   val: "'disabled'"

    # Disabling: Because conflicts with Dubs Vim and tmux key bindings.
    #            - And I don't use mate-terminal tabs,
    #              nor do I use more than one profile.

    # "Move Tab to the Left"
    # Default: Shift+Ctrl+Page Up
    - key: "move-tab-left"
      val: "'disabled'"

    # "Move Tab to the Right"
    # Default: Shift+Ctrl+Page Down
    - key: "move-tab-right"
      val: "'disabled'"

    # "Switch to Next Tab"
    # Default: Ctrl+Page Down
    - key: "next-tab"
      val: "'disabled'"

    # "Switch to Previous Tab"
    # Default: Ctrl+Page Up
    - key: "prev-tab"
      val: "'disabled'"

    # "Switch to Tab 1"
    # Default: Alt+1
    - key: "switch-to-tab-1"
      val: "'disabled'"

    # "Switch to Tab 2"
    # Default: Alt+2
    - key: "switch-to-tab-2"
      val: "'disabled'"

    # "Switch to Tab 3"
    # Default: Alt+3
    - key: "switch-to-tab-3"
      val: "'disabled'"

    # "Switch to Tab 4"
    # Default: Alt+4
    - key: "switch-to-tab-4"
      val: "'disabled'"

    # "Switch to Tab 5"
    # Default: Alt+5
    - key: "switch-to-tab-5"
      val: "'disabled'"

    # "Switch to Tab 6"
    # Default: Alt+6
    - key: "switch-to-tab-6"
      val: "'disabled'"

    # "Switch to Tab 7"
    # Default: Alt+7
    - key: "switch-to-tab-7"
      val: "'disabled'"

    # "Switch to Tab 8"
    # Default: Alt+8
    - key: "switch-to-tab-8"
      val: "'disabled'"

    # "Switch to Tab 9"
    # Default: Alt+9
    - key: "switch-to-tab-9"
      val: "'disabled'"

    # "Switch to Tab 10"
    # Default: Alt+0
    - key: "switch-to-tab-10"
      val: "'disabled'"

    # # "Switch to Tab 11"
    # # Default: disabled
    # - key: "switch-to-tab-11"
    #   val: "'disabled'"

    # # "Switch to Tab 12"
    # # Default: disabled
    # - key: "switch-to-tab-12"
    #   val: "'disabled'"

    # **** Shortcut keys > Terminal

    # # "Reset"
    # # Default: disabled
    # - key: "reset"
    #   val: "'disabled'"

    # # "Reset and Clear
    # # Default: disabled
    # - key: "reset-and-clear"
    #   val: "'disabled'"

    # # "Set Title"
    # # Default: disabled
    # - key: "set-terminal-title"
    #   val: "'disabled'"

    # "Switch to Next Profile"
    # Default: Alt+Page Down
    - key: "next-profile"
      val: "'disabled'"

    # "Switch to Previous Profile"
    # Default: Alt+Page Up
    - key: "prev-profile"
      val: "'disabled'"

    # **** Shortcut keys > View 

    # (lb): 2020-02-11: Leave this'un?
    #
    # # "Full Screen"
    # # Default: F11
    # - key: ""
    #   val: "'disabled'"

    # # "Hide and Show menubar"
    # # Default: disabled
    # - key: "toggle-menubar"
    #   val: "'disabled'"

    # (lb): I don't think I ever use zoom controls
    # except when I boxing-glove zoom in or zoom out
    # by accident and need to then deliberately Ctrl+0
    # to restore the normal (no) zoom size.
    # - 2020-02-18: On second thought, they're
    #   useful when presenting!!

    # # "Normal Size
    # # Default: Ctrl+0
    # - key: "zoom-normal"
    #   val: "'disabled'"

    # # "Zoom In
    # # Default: Ctrl+
    # - key: "zoom-in"
    #   val: "'disabled'"

    # # "Zoom Out
    # # Default: Ctrl+-
    # - key: "zoom-out"
    #   val: "'disabled'"

# Unlike Profile Preferences, Keyboard Bindings changes effective immediately.

